#### general settings
name: Pretrain_FT_TOF_V_S2_0420_1x3
use_tb_logger: true
model: video_base
distortion: sr
scale: 2
gpu_ids: [1] # [0,1,2,3,4,5,6,7]
kernel_size: 21
#### datasets
datasets:
  train:
    name: Vimeo
    mode: Vimeo
    interval_list: [1]
    random_reverse: false
    border_mode: false
    data_root: 'F:/'
    img_type: img

    N_frames: 7
    use_shuffle: true
    n_workers: 3  # per GPU
    batch_size: 25 #15
    patch_size: 64
    use_flip: true
    use_rot: true
    color: RGB
    kernel_size: 21
  val:
    name: Vid4 #+REDS
    mode: video_test
    dataroot_GT: F:/Vid4/GT #+../dataset/REDS/train/HR
    dataroot_LQ: F:/Vid4/DUF_0404/LR_preset #+../dataset/REDS/train/LR_bicubic
    cache_data: True
    N_frames: 7
    padding: new_info
    degradation_mode: set
    sigma_x: 0.4
    sigma_y: 2.0
    theta: 0

sigma_x: 0.4 # up and below all revised
sigma_y: 2.0
theta: 0
#### network structures
network_G:
  which_model_G: TOF

network_E:
  which_model_E: ~
#### path
path:
  pretrain_model_G: F:/DynaVSR-master/pretrained_models/TOF/Vid4_G.pth
  strict_load: False
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-4 # 4e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  epochs: 1000
  niter: 10000
  warmup_iter: -1  # -1: no warm up
  lr_steps: [50000, 75000]
  lr_gamma: 0.2

  pixel_criterion: l1
  pixel_weight: 1.0
  # val_freq: !!float 5000 # 1e3
  val_freq: !!float 10000 # 1e3

  manual_seed: 0

#### logger
logger:
  print_freq: 500
  save_checkpoint_freq: !!float 2500 #5e3
