#### general settings
name: Pretrain_EDVR_M_lr1e-4_600k_reds_S2
use_tb_logger: true
model: video_base
distortion: sr
scale: 2
gpu_ids: [2] # [0,1,2,3,4,5,6,7]

#### datasets
datasets:
  train:
    name: REDS
    mode: REDS
    interval_list: [1]
    random_reverse: false
    border_mode: false
    data_root: '../dataset'
    img_type: bin

    N_frames: 5
    use_shuffle: true
    n_workers: 3  # per GPU
    batch_size: 4
    patch_size: 48
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: REDS
    mode: video_test
    dataroot_GT: ../dataset/REDS/train/HR
    dataroot_LQ: ../dataset/REDS/train/LR_bicubic
    cache_data: True
    N_frames: 5
    padding: new_info

#### network structures
network_G:
  which_model_G: EDVR
  nf: 64
  nframes: 5
  groups: 8
  front_RBs: 5
  back_RBs: 10
  predeblur: false
  HR_in: false
  w_TSA: true

#### path
path:
  pretrain_model_G: ../experiments/pretrained_models/EDVR_REDS_SR_M_Scale2.pth
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4 # 4e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  epochs: 1000
  niter: 600000
  ft_tsa_only: 50000
  warmup_iter: -1  # -1: no warm up
  T_period: [50000, 100000, 150000, 150000, 150000]
  restarts: [50000, 150000, 300000, 450000]
  restart_weights: [1, 1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 1e3

  manual_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
