#### general settings
name: BasicVSR
use_tb_logger: true
model: video_base
distortion: sr
scale: 4
gpu_ids: [1] # [0,1,2,3,4,5,6,7]
kernel_size: 21

#### datasets
datasets:
  train:
    name: REDS
    mode: video_test
    interval_list: [1]
    random_reverse: false
    border_mode: false
    data_root: 'F:/'
    img_type: img
    N_frames: 5
    use_shuffle: true
    n_workers: 3  # per GPU
    batch_size: 6
    patch_size: 48
    use_flip: true
    use_rot: true
    color: RGB
    kernel_size: 21

  val:
    name: Vid4
    mode: video_test
    dataroot_GT: C:/Users/user/Desktop/BasicVSR_PlusPlus-master/REDS/REDS4 #+../dataset/REDS/train/HR
    dataroot_LQ: C:/Users/user/Desktop/BasicVSR_PlusPlus-master/REDS/REDS4 #+../dataset/REDS/train/LR_bicubic
    cache_data: True
    N_frames: 5
    padding: new_info
    degradation_mode: set
    sigma_x: 2.0
    sigma_y: 0.4
    theta: 0

sigma_x: 2.0 # up and below all revised
sigma_y: 0.4
theta: 0
#### network structures
network_G:
  which_model_G: BasicVSRplus
  nf: 64
  nframes: 5
  groups: 8
  front_RBs: 5
  back_RBs: 10
  predeblur: false
  HR_in: false
  w_TSA: true

network_E:
  which_model_E: ~
  
#### path
path:
  pretrain_model_G: ../pretrained_models/EDVR/Vid4_G.pth
  strict_load: False
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4 # 4e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  epochs: 1000
  niter: 10000
  ft_tsa_only: 50000
  warmup_iter: -1  # -1: no warm up
  T_period: [50000, 100000, 150000, 150000, 150000]
  restarts: [50000, 150000, 300000, 450000]
  restart_weights: [1, 1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 5000

  manual_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: 5000
