#### general settings
name: R_R4_DUF_16L_vid
use_tb_logger: true
model: video_base+lrimgestimator
distortion: sr
scale: 2
cpu: false
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: REDS
    mode: video_test
    interval_list: [1]
    random_reverse: false
    border_mode: false7
    data_root: '../dataset'
    cache_data: True
    padding: new_info
    img_type: img

    N_frames: 7
    use_shuffle: true
    n_workers: 3  # per GPU
    batch_size: 4
    patch_size: 192
    kernel_size: 21
    use_flip: true
    use_rot: true
    color: RGB


  val:
    name: REDS+REDS+REDS+REDS+REDS+REDS
    mode: benchmark
    dataroot_GT: ../dataset/REDS/train/HR+../dataset/REDS/train/HR+../dataset/REDS/train/HR+../dataset/REDS/train/HR+../dataset/REDS/train/HR+../dataset/REDS/train/HR
    dataroot_LQ: ../dataset/REDS/train/LR+../dataset/REDS/train/LR+../dataset/REDS/train/LR+../dataset/REDS/train/LR+../dataset/REDS/train/LR+../dataset/REDS/train/LR
    cache_data: True
    N_frames: 7
    #patch_size: 56
    padding: new_info
  
    degradation_mode: set
    degradation_type: bicubic+bicubic+bicubic+impulse+impulse+impulse
    sigma_x: 0.8+1.2+1.6+0.8+1.2+1.6
    sigma_y: 0.8+1.2+1.6+0.8+1.2+1.6
    theta: 0.0+0.0+0.0+0.0+0.0+0.0

#### network structures
network_G:
  which_model_G: DUF
  layers: 16

network_E:
  which_model_E: MFDN
  mode: video
  nf: 64
  in_nc: 3

#### path
path:
  pretrain_model_G: ../pretrained_models/BaselineVSR/DUF_16L_REDS_S2.pth
  pretrain_model_E: ../pretrained_models/MFDN/MFDN_REDS.pth
  strict_load: true
  resume_state: ~
  img_save_path: ../results

#### training settings: learning rate scheme, loss
train:
  lr_C: !!float 1e-4 # Not Used
  lr_G: !!float 1e-5
  lr_scheme: MultiStepLR
  optim: Adam
  beta1: 0.9
  beta2: 0.99
  epochs: 20
  niter: 30000
  warmup_iter: -1  # -1: no warm up
  lr_steps: [20000, 25000]
  lr_gamma: 0.2
  loss_ftn: l1  # Loss function for updating KE model
  use_real: false

  maml:
    use_patch: false
    num_patch: 3
    patch_size: 96
    optimizer: Adam
    lr_alpha: !!float 1e-5
    beta1: 0.9
    beta2: 0.99
    adapt_iter: 1

  pixel_criterion: huber
  pixel_weight: 1.0
  val_freq: !!float 1000

  manual_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1000
