#### general settings
name: V_V4_EDVR_LRI
use_tb_logger: true
model: video_base+lrimgestimator
distortion: sr
scale: 2
cpu: false
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: Vimeo
    mode: video_test
    interval_list: [1]
    random_reverse: false
    border_mode: false7
    data_root: '../dataset'
    cache_data: True
    padding: new_info
    img_type: img

    N_frames: 5
    use_shuffle: true
    n_workers: 3  # per GPU
    batch_size: 4
    patch_size: 128
    kernel_size: 21
    use_flip: true
    use_rot: true
    color: RGB


  val:
   name: Vid4
   mode: benchmark #video_test
   dataroot_GT: ../dataset/Vid4/HR
   dataroot_LQ: ../dataset/Vid4/LR #_bicubic
   cache_data: True
   N_frames: 5
   #patch_size: 56
   padding: new_info

   degradation_mode: set
   degradation_type: bicubic
   sigma_x: 1.2
   sigma_y: 1.2
   theta: 0

#### network structures
network_G:
  which_model_G: EDVR
  nf: 64
  nframes: 5
  groups: 8
  front_RBs: 5
  back_RBs: 10
  predeblur: false
  HR_in: false
  w_TSA: true

network_E:
  which_model_E: SFDN
  mode: image
  nf: 64


#### path
path:
  pretrain_model_G: ../pretrained_models/BaselineVSR/EDVR_M_Vimeo_S2.pth
  pretrain_model_E: ../pretrained_models/MFDN/SFDN_Vimeo.pth
  strict_load: true
  resume_state: ~
  img_save_path: ../results

#### training settings: learning rate scheme, loss
train:
  lr_C: !!float 1e-4 # Not Used
  lr_G: !!float 1e-6
  lr_scheme: MultiStepLR
  optim: Adam
  beta1: 0.9
  beta2: 0.99
  epochs: 20
  niter: 30000
  warmup_iter: -1  # -1: no warm up
  lr_steps: [10000, 20000]
  lr_gamma: 0.2
  loss_ftn: l1  # Loss function for updating KE model
  use_real: false

  maml:
    use_patch: false
    num_patch: 1
    patch_size: 128
    optimizer: Adam
    lr_alpha: !!float 1e-6
    beta1: 0.9
    beta2: 0.99
    adapt_iter: 1

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 1e3

  manual_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e3
